name: freetask_app
description: Freetask application for marketplace services.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  bloc: ^8.1.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  uuid: ^4.5.0
  socket_io_client: ^2.0.3+1
  path: ^1.9.0
  mime: ^1.0.5
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  sentry_flutter: ^8.7.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.6
  mocktail: ^1.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
